- mane: CD
- job:
- build: 
- step: 
     - run-on: Ubuntu-latest
- name: Checkout
  uses: actions/checkout@v3

- name: Checkout tools repo
  uses: actions/checkout@v3
  with:
    repository: my-org/my-tools
    path: my-tools
