name: Windows CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  Windows:
    name: Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        architecture:
          # - '32'
          - '64'

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Git checkout
        uses: actions/checkout@v2

      - name: Upload Installer
        uses: actions/upload-artifact@v2
        with:
          name: windows-installer
          path: artifacts
          if-no-files-found: ignore
